#!/usr/bin/env python3
"""Regenerate INDEX.md from idea frontmatter. GENERATED FILE — never hand-edited, by human or model.

This is what makes parallel agents safe: nobody writes a shared mutable index, so nobody conflicts.
"""
import nichelib as nl
from collections import Counter

ORDER = ["validated","promoted","sandbox","falsified","demoted","duplicate"]

def main():
    ideas = nl.all_ideas()
    counts = Counter(m.get("status","?") for _, m, _ in ideas)
    cells = nl.jsonl(nl.FRONTIER / "cells.jsonl")
    swept = sum(1 for c in cells if c.get("last_swept"))
    out = ["# Index", "", "<!-- GENERATED by scripts/build_index.py — do not edit by hand -->", "",
           f"Frontier coverage: **{swept} / {len(cells)}** cells swept "
           f"({(100*swept/len(cells) if cells else 0):.1f}%)", "",
           "| status | count |", "|---|---|"]
    for s in ORDER:
        if counts.get(s): out.append(f"| {s} | {counts[s]} |")
    out += ["", "## Ideas", ""]
    for s in ORDER:
        rows = [(f, m) for f, m, _ in ideas if m.get("status") == s]
        if not rows: continue
        out += [f"### {s} ({len(rows)})", "",
                "| slug | cell | score | tier | persistence |", "|---|---|---|---|---|"]
        for f, m in sorted(rows, key=lambda t: -(t[1].get("composite") or 0)):
            out.append(f"| [{m.get('slug', f.stem)}](ideas/{f.name}) | {m.get('cell_id','–')} | "
                       f"{m.get('composite','–')} | {m.get('evidence_tier','–')} | "
                       f"{m.get('persistence','–')} |")
        out.append("")
    (nl.ROOT / "INDEX.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"INDEX.md regenerated: {len(ideas)} ideas, {swept}/{len(cells)} cells swept")

if __name__ == "__main__":
    main()
